### PR TITLE
Temporarily fix breaking build with setuptools v69

### PR DESCRIPTION
**Pull request by somnam**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://faust-streaming.github.io/faust/contributing.html).

## Description
Temporarily fix breaking build with setuptools v69

https://github.com/faust-streaming/faust/issues/570

NOTE: All patches should be made against master, not a maintenance branch like
3.1, 2.5, etc.  That is unless the bug is already fixed in master, but not in
that version series.

If it fixes a bug or resolves a feature request,
be sure to link to that issue via (Fixes #4412) for example.

### CODE REVIEW

**Review by wbarnha — APPROVED** [review]
Thanks for the PR, LGTM while I figure out what's going on with this.

**Comment by somnam** [comment]
Thanks for merging! Will there be a new release with this fix?

**Comment by wbarnha** [comment]
I'm in an awkward spot right now with getting a 3.12 release out. Is it blocking you from installing Faust?

**Comment by somnam** [comment]
> I'm in an awkward spot right now with getting a 3.12 release out. Is it blocking you from installing Faust?

On M1 Macs or aarch images it's kind of impossible now due to this bug.
I've worked around it by doing a local wheel build and installing that when on arm/aarch architecture, but it's kind of hacky.

**Comment by wbarnha** [comment]
My condolences, let's get that release out for you.

**Pull request merged**
