### PR TITLE
Restore tests (updated)

### PR DESCRIPTION
**Pull request by taybin**
## Description

This is an updated version of https://github.com/faust-streaming/faust/pull/30, with master merged in.

### CODE REVIEW

**Comment by taybin** [comment]
It's failing because the code coverage is 59%, less than the 60% required. :/

**Comment by taybin** [comment]
@forsberg What is the purpose of the `python_classes = test_*` line?  To include or exclude tests?  Because the default is `Test*` and the majority of test classes start with `Test_`, but some also start with `Test[A-Z]`.

**Comment by bobh66** [comment]
@taybin - the original faust project used class names that started with "test_" to the python_classes option was required for pytest to work.  Later changes used the Test class names but until everything gets converted the python_classes is still needed.

**Comment by taybin** [comment]
@bobh66 okay, thanks.  There's only one test with the `test_` naming, so I'll just rename that one and remove the `python_classes =` line.

**Comment by taybin** [comment]
I'm not in a hurry to merge this as I'm working on restoring the aiokafka driver tests in #143 and I'm not fully getting some of the changes yet.

**Review by patkivikram — APPROVED** [review]

**Pull request merged**
