### PR TITLE
fix: ensure aiokafka commit is called with kafka.structs.TopicPartiti…

### LINKED ISSUE #539: Commit structure validation failure: TP != TopicPartition
I found a puzzling issue.

Both aiokafka and faust define named tuples for `(topic, partition)`, namely `TopicPartition` and `TP` respectively. The faust one doesn't satisfy the `isinstance` check in aiokafka's `commit_structure_validate` and so the stack trace below occurs. What I don't understand is how this ever worked. Why do I only see this now? Is this some unusual commit path?

Either way, a faust `TP` is not a aiokafka `TopicPartition` according to `isinstance`, so this must be a bug.

```python
ERROR:faust.transport.drivers.aiokafka:[^--AIOKafkaConsumerThread]: Got exception: ValueError('Key should be TopicPartition instance')
Current assignment: {TP(topic='test-uploads', partition=0), TP(topic='test-dgtal-cases-documents-list-changelog', partition=0), TP(topic='test-dgtal.worker.agents.health_agent', partition=0), TP(topic='test-transactions', partition=0), TP(topic='dgtal-reply-to', partition=0), TP(topic='test-actions', partition=0), TP(topic='test-dgtal-documents-changelog', partition=0), TP(topic='test-__assignor-__leader', partition=0), TP(topic='test-documents', partition=0), TP(topic='test-events', partition=0), TP(topic='test-cases', partition=0), TP(topic='test-dgtal-transactions-changelog', partition=0), TP(topic='test-dgtal-cases-changelog', partition=0), TP(topic='test-cases-index', partition=0), TP(topic='test-dgtal-cases-transactions-list-changelog', partition=0)}, detail: {TP(topic='test-events', partition=0): OffsetAndMetadata(offset=3, metadata='')}
Traceback (most recent call last):
  File "/home/richard/Work/dgtal/.venv/lib/python3.10/site-packages/faust/transport/drivers/aiokafka.py", line 721, in _commit
    await consumer.commit(aiokafka_offsets)
  File "/home/richard/Work/dgtal/.venv/lib/python3.10/site-packages/aiokafka/consumer/consumer.py", line 562, in commit
    offsets = commit_structure_validate(offsets)
  File "/home/richard/Work/dgtal/.venv/lib/python3.10/site-packages/aiokafka/util.py", line 63, in commit_structure_validate
    raise ValueError("Key should be TopicPartition instance")
ValueError: Key should be TopicPartition instance
ERROR:faust.transport.drivers.aiokafka:[^--AIOKafkaConsumerThread]: Crashed reason=ValueError('Key should be TopicPartition instance')
Traceback (most recent call last):
  File "/home/richard/Work/dgtal/.venv/lib/python3.10/site-packages/faust/transport/drivers/aiokafka.py", line 721, in _commit
    await consumer.commit(aiokafka_offsets)
  File "/home/richard/Work/dgtal/.venv/lib/python3.10/site-packages/aiokafka/consumer/consumer.py", line 562, in commit
    offsets = commit_structure_validate(offsets)
  File "/home/richard/Work/dgtal/.venv/lib/python3.10/site-packages/aiokafka/util.py", line 63, in commit_structure_validate
    raise ValueError("Key should be TopicPartition instance")
ValueError: Key should be TopicPartition instance
```

### PR DESCRIPTION
**Pull request by dabdada**
Make sure `AIOKafkaConsumer.commit()` receives compatible TopicPartition class. (Fixes #539)

### CODE REVIEW

**Comment by wbarnha** [comment]
Thanks for spending the time investigating this, you wouldn't believe how much of a favor this is. Lint the PR and it should be good!

**Review by wbarnha — APPROVED** [review]
Weird, this seems to have fixed the PyPy tests as well? I've never seen them pass before in CI/CD. Thank you, LGTM!

**Comment by wbarnha** [comment]
Wait, it seems the PyPy test is erroneously marked as passing. I wonder if something in the workflow logic got updated to mark as passing when experimental.

**Comment by dabdada** [comment]
Didn't do anything related to that. Should I?

**Comment by wbarnha** [comment]
> Didn't do anything related to that. Should I?

No need for concern on your end, just got excited too soon about PyPy tests.

**Pull request merged**
