### PR TITLE
Additional broker configs

### PR DESCRIPTION
**Pull request by magzot**
* connections_max_idle
* metadata_max_age

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://faust.readthedocs.io/en/master/contributing.html).

## Description

Need a way to specify aiokafka.consumer and .producer settings **connections_max_idle_ms** and **metadata_max_age_ms**

### CODE REVIEW

**Review by patkivikram — APPROVED** [review]

**Comment by magzot** [comment]
@patkivikram Hi, thanks for approving! But didn't quite understand if it passed the linting step or not. Did another commit to fix that. Or is it already merged?

**Comment by patkivikram** [comment]
looks like there are some conflicts. Can you fix that and push your changes?

**Comment by Roman1us** [comment]
This PR duplicates some of settings already merged in #279. Can you check this?

**Comment by magzot** [comment]
Ok, the same setting was added but in a slightly different way. Will abandon and create a new pull request with the missing setting following the style of #279. I added a broker_ setting but #279 implemented as consumer + producer settings.

**Pull request closed without merging**
