### PR TITLE
Add FastAPI example

### PR DESCRIPTION
**Pull request by wbarnha**
There's been an increase in demand for this and I've personally been meaning to add this for some time.

### CODE REVIEW

**Comment by chanpl** [comment]
Thanks @wbarnha for providing the example. Can you also please provide an example for medium/large project? In my case, consumers are not subscribing any topics if agent is defined in a separate file.

**Comment by hgalytoby** [comment]
> Thanks @wbarnha for providing the example. Can you also please provide an example for medium/large project? In my case, consumers are not subscribing any topics if agent is defined in a separate file.

For reference?

https://github.com/faust-streaming/faust/pull/595

**Comment by hgalytoby** [comment]
> There's been an increase in demand for this and I've personally been meaning to add this for some time.

@wbarnha 

I've added a new FastAPI example, could you take a look?

**Comment by wbarnha** [comment]
Sure! Thanks for adding it!

**Comment by chanpl** [comment]
@wbarnha Thank you very much! I really appreciate it.

**Pull request merged**
