### PR TITLE
Add a TTL for RocksDB store

### LINKED ISSUE #515: Table TTL
Hi All,

This is more of a question than an issue  - not sure if you have a community channel instead?

i see someone posted on the original faust repo, asking if and how we can expire table entries using TTL in 2018 - https://github.com/robinhood/faust/issues/230 . Has this feature been implemented?  This would be handy to prevent table bloat over time, when not using windowed tables.

### PR DESCRIPTION
**Pull request by YiuRULE**
## Description

Add TTL for faust stores.
Fixes #515

### CODE REVIEW

**Review by wbarnha — COMMENTED** [review]
I'm definitely for adding this feature but I'm wondering if we should allow more options to be specified while we're at it. Could you so provide an example in the docstring as to how this should be utilized?

**Comment by wbarnha** [comment]
Cheers, thanks for the example! I'll review it further when I get to a proper computer in the morning before merging.

**Comment by YiuRULE** [comment]
I add some documentation on the latest revision, let me know if it's ok :)
And also if you wish to add something more if needed to

**Review by wbarnha — APPROVED** [review]
Good stuff, thanks for the PR!

**Pull request merged**
