### PR TITLE
Fix potential NoneType access in aiokafka driver

### PR DESCRIPTION
**Pull request by GodTamIt**
## Description

This logic is likely meant to be a boolean `OR` not `AND`, since the first check in the statement checks for `assignment` to be `None`.

### CODE REVIEW

**Review by wbarnha — APPROVED** [review]
Genuinely surprised how such a simple thing got overlooked for so long. Makes sense to change it to this.

What caused you to stumble upon this, out of curiosity @GodTamIt?

**Comment by wbarnha** [comment]
Ah crud... looks like I need to go clean up the pyproject.toml file. I promised myself I'd finish switching things over eventually, but now my hand is forced.

**Comment by GodTamIt** [comment]
> Genuinely surprised how such a simple thing got overlooked for so long. Makes sense to change it to this.
> 
> What caused you to stumble upon this, out of curiosity @GodTamIt?

@wbarnha I was running the test in https://github.com/faust-streaming/faust/pull/568 for long enough that it hit this edge case.

It was quite hard to reproduce actually.

**Comment by wbarnha** [comment]
> > Genuinely surprised how such a simple thing got overlooked for so long. Makes sense to change it to this.
> > 
> > What caused you to stumble upon this, out of curiosity @GodTamIt?
> 
> @wbarnha I was running the test in https://github.com/faust-streaming/faust/pull/568 for long enough that it hit this edge case.
> 
> It was quite hard to reproduce actually.

Thank you for finding this! I'll merge it ASAP.

**Pull request merged**
