### PR TITLE
Producer: Rewrite non enabled unit tests

### PR DESCRIPTION
**Pull request by cbrand**
## Description

During the implementation of https://github.com/faust-streaming/faust/pull/270 I realized that a couple of unit tests inside of the tests/unit/transport/test_producer.py doesn't do anything due to early return statements.

This PR adjusts all the tests to check for expected behavior which did not run correctly before.

Open Question is the `flush_atmost` function. Due to the event set wait method, it cannot be guaranteed that during the flush operation that there are at max the max_messages of sent events being sent. According to the function name and the previous test, however, this is the intended behavior.

I adjusted the test accordingly and just expect that messages are sent out, as there doesn't seem to be a reasonable primitive to fulfill the existing expectation within the test.

### CODE REVIEW

**Review by patkivikram — APPROVED** [review]

**Comment by cbrand** [comment]
@patkivikram hopefully fixed the formatting issues (i only ran black on the faust repository and not the tests repository accidentally).

**Comment by patkivikram** [comment]
@cbrand can you resolve the conflicts?

**Comment by cbrand** [comment]
Yes, will do and I will get back to you.

**Comment by cbrand** [comment]
@patkivikram done. Please check. I also realized that it seems that the `ThreadedProducer` isn't tested at all as it would currently fail in Python 3.6 (as it uses asyncio.create_task). See: https://github.com/faust-streaming/faust/pull/277 for a potential solution there.

**Pull request merged**
