### PR TITLE
Add method to RocksDB for backing up partitions

### PR DESCRIPTION
**Pull request by wbarnha**
I have a specific use-case where I need to actively backup a RocksDB store. I've had success using `rocksdb.BackupEngine` with `faust` but it'd be much more usable if the code was integrated into `faust`.

I should note I've only had success with this using `librocksdb-dev==6.11.4-3` on Ubuntu 22.04 and the python-rocksdb bindings from https://github.com/NightTsarina/python-rocksdb.

If you have interest in this, let me know because I really need this feature.

### CODE REVIEW

**Comment by wbarnha** [comment]
I'm satisfied with the changes I have now. If you have any other changes you'd like to see, let me know.

**Comment by wbarnha** [comment]
I forgot to test some last-minute changes earlier. I've tested everything and runs properly now.

**Comment by wbarnha** [comment]
Removed import of `BackupEngine` to pass lint check, should be good now...

**Comment by wbarnha** [comment]
I'm not sure where this should be added, but according to https://fauststream.slack.com/archives/C7FL9CB5E/p1594816114113200?thread_ts=1594815786.109000&cid=C7FL9CB5E, recoveries are automatically triggered when a table is accessed. After testing further, it seems that calling `restore_backup` is equally safe as calling it during initialization or in asynchronous tasks that startup upon app initialization. Still haven't tested periodically restoring backups while the app is initialized since I haven't needed to do that.

**Comment by wbarnha** [comment]
On further testing, it appears that the current release of https://github.com/faust-streaming/python-rocksdb is fine for accessing the backup functions in `librocksdb-dev`. For older versions that are released such as 5.8.8, I got errors along the lines of `rocksdb.error.NotImplementedError`. We may want to add a disclaimer that the backup options are only available in specific versions of librocksdb.

**Review by patkivikram — APPROVED** [review]

**Pull request merged**
