### PR TITLE
Rename kafka to aiokafka

### PR DESCRIPTION
**Pull request by AntonOfTheWoods**
kafka-python is no longer to be a dependency of aiokafka

Following https://github.com/aio-libs/aiokafka/discussions/915

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://faust-streaming.github.io/faust/contributing.html).

## Description

Please describe your pull request.

NOTE: All patches should be made against master, not a maintenance branch like
3.1, 2.5, etc.  That is unless the bug is already fixed in master, but not in
that version series.

If it fixes a bug or resolves a feature request,
be sure to link to that issue via (Fixes #4412) for example.

### CODE REVIEW

**Comment by wbarnha** [comment]
Indeed it is not! Thanks for the PR!

**Comment by wbarnha** [comment]
```python
 faust/transport/drivers/aiokafka.py:39: in <module>
    from aiokafka.coordinator.assignors.roundrobin import RoundRobinPartitionAssignor
E   ModuleNotFoundError: No module named 'aiokafka.coordinator'
```
Looks like it's not an end-all-be-all solution like I'd hoped :frowning:

**Comment by AntonOfTheWoods** [comment]
They (annoyingly) moved some classes. Sorry, looks like I missed one or two.

**Comment by AntonOfTheWoods** [comment]
Actually @wbarnha where did that stacktrace come from? If from the tests it's not going to work, because it doesn't point to the as-yet-unreleased `master` branch of `aiokafka`. This PR should actually work for code that points to the upcoming version.

**Comment by wbarnha** [comment]
Ugh, Faust is in a rough spot right now. I need to get a release for `kafka-python` onto PyPi in order to get support for 3.12 in the meantime. This stinks.

**Comment by AntonOfTheWoods** [comment]
> Ugh, Faust is in a rough spot right now. I need to get a release for `kafka-python` onto PyPi in order to get support for 3.12 in the meantime. This stinks.

Yeah, I would just let kafka-python die. I doubt (unless maybe if you kick up a stink) that aiokafka will be interested in adding kafka-python back as a dep, so the way forward seems to be to focus on getting aiokafka stable for 3.12 and giving Kafka-python a 3 gun salute...

**Comment by wbarnha** [comment]
I'm currently in the works of reaching out to the original maintainer of kafka-python. If I don't hear back after early December, additional action will be taken. There have been internal discussions and none of us want to see the project die. The other maintainers have been less active since they don't currently use it but still appreciate its importance, hence why I was appointed.

The problem is getting PyPi access...

**Comment by wbarnha** [comment]
```python3

Run scripts/tests
+ [ -z true ]
+ pytest tests/unit tests/functional tests/integration tests/meticulous/ tests/regression
ImportError while loading conftest '/home/runner/work/faust/faust/tests/unit/conftest.py'.
tests/unit/conftest.py:7: in <module>
    from faust.transport.producer import Producer
faust/transport/__init__.py:2: in <module>
    from .drivers import by_name, by_url
faust/transport/drivers/__init__.py:4: in <module>
    from .aiokafka import Transport as AIOKafkaTransport
faust/transport/drivers/aiokafka.py:39: in <module>
    from aiokafka.coordinator.assignors.roundrobin import RoundRobinPartitionAssignor
E   ModuleNotFoundError: No module named 'aiokafka.coordinator'
```
Welp, I was hoping the latest `aiokafka` release would magically fix my problems. Looks like some legwork will need to be done.

**Comment by AntonOfTheWoods** [comment]
https://github.com/aio-libs/aiokafka/blob/master/aiokafka/coordinator/assignors/roundrobin.py

Again, are you sure the tests are pointing to the updated version?

**Comment by wbarnha** [comment]
Good question, I'll need to check when I get the opportunity. Thank you for being patient, I've been extremely busy as of late.

**Comment by wbarnha** [comment]
Thanks for updating the PR! LGTM.

**Review by wbarnha — APPROVED** [review]

**Pull request merged**
