### PR TITLE
Python 3.10

### PR DESCRIPTION
**Pull request by taybin**
This builds off of #204 to remove the deprecated loop argument that was finally removed in python-3.10.

~It uses an unreleased version of mode so probably blocked on releasing mode-0.2.0, but the tests pass.~

### CODE REVIEW

**Review by austinnichols101 — DISMISSED** [review]
I made a couple of notes for your review...

**Comment by PushUpek** [comment]
any chance to merge this PR soon?

**Comment by theY4Kman** [comment]
I see [mode-streaming](https://pypi.org/project/mode-streaming/) lists @taybin as maintainer, with a release from last week, and I'm very excited. Where must I send my cryptokitties to shepherd this along? Or I can do your laundry? Mow your lawn? Hell, I'll floss your teeth for you, or floss _my_ teeth in your stead, with an official note to pass to your dentist!

**Comment by AntonOfTheWoods** [comment]
@taybin , is there anything stopping this being pointed to the new streaming?

**Comment by blazing-gig** [comment]
@taybin Would love for this PR to get merged ASAP as there doesn't seem to be any blockers.

**Comment by theY4Kman** [comment]
whose back do i gotta scratch to apply a diff?
```diff
diff --git a/faust/streams.py b/faust/streams.py
index 111be051..c87db350 100644
--- a/faust/streams.py
+++ b/faust/streams.py
@@ -414,8 +414,8 @@ class Stream(StreamT[T_co], Service):
         buffer_add = buffer.append
         event_add = events.append
         buffer_size = buffer.__len__
-        buffer_full = asyncio.Event(loop=self.loop)
-        buffer_consumed = asyncio.Event(loop=self.loop)
+        buffer_full = asyncio.Event()
+        buffer_consumed = asyncio.Event()
         timeout = want_seconds(within) if within else None
         stream_enable_acks: bool = self.enable_acks
```

**Comment by taybin** [comment]
Okay, the tests are passing.  I suppose now we just need a PR approval and merge and then a beta release for trying it out.

**Comment by taybin** [comment]
@patkivikram What do you think?  Can this get merged?

**Comment by VikalpRusia** [comment]
@patkivikram @austinnichols101 any update on this?

**Comment by AntonOfTheWoods** [comment]
Am I missing something here? It looks as though all the work has been done, there is reasonable interest from the community but maintainers are just *ignoring* it. It is not that the maintainers are MIA, they are just (actively?) *ignoring* this. No mention of "you forgot ABC" or "we need better testing" or even "we don't want this on grounds of principle because XYZ".

Is there something political I am missing here? Is there something dubious with 3.10 that I have failed to find?

**Comment by VikalpRusia** [comment]
We have decided to fork the original Faust project because there is a critical process of releasing new versions which causes uncertainty in the community. Everybody is welcome to contribute to this fork, and you can be added as a manitainer.

Whats the meaning of this line in README.md when you are also acting like original faust !

**Comment by blazing-gig** [comment]
@AntonOfTheWoods Cant agree more... Would definitely like this to get merged.

**Review by austinnichols101 — APPROVED** [review]

**Comment by AntonOfTheWoods** [comment]
Thank you @austinnichols101 and @taybin !!!

**Comment by VikalpRusia** [comment]
When we are releasing this?
I need to use it ASAP

**Pull request merged**
