### PR TITLE
Take with timestamp

### PR DESCRIPTION
**Pull request by nicor88**
# Add take_with_timestamp

## Description

I'm currently using the take method of a stream in production. I have some cases where I would like to have not only the batch of values but a batch of values with the timestamp of when the message was inserted into kafka.

This PR adds a new method called take_with_timestamp, it works exactly like take, but it adds the Kafka timestamp to each returned value.

I tested in a local environment and seems working as expected, the real difference with take is this: 
```
value[timestamp_field_name] = event.message.timestamp
```
the name of the timestamp must be passed as an argument, to force to pass the name, some people might like kafka_timestamp, some event_timestamp, I preferred to leave it generic.

### CODE REVIEW

**Comment by nicor88** [comment]
@patkivikram and @ekerstens I saw that you are pretty active, could you have a look? 🙏

**Comment by taybin** [comment]
The code looks clean to me, but I think for a user facing function, there really needs to be a unit test of some kind for it.

**Comment by nicor88** [comment]
@taybin could you have a look again? I added 3 tests, should cover the most essentials parts.

**Comment by nicor88** [comment]
@patkivikram if you have some time to look into that would be amazing, it's pretty trivial. Many thanks.

**Review by patkivikram — APPROVED** [review]

**Pull request merged**
