### PR TITLE
Add override_logging argument to Worker (#634)

### PR DESCRIPTION
**Pull request by lpogo**
* Add override_logging argument to Worker 
* Add worker_override_logging to App
* Update documentation
* Update tests

## Description

Allow user to decide if override_logging shoud be enabled or not.
It is forced by faust.Worker to be enabled right now.

It resolve Issue #634

### CODE REVIEW

**Comment by lpogo** [comment]
@patkivikram, @wbarnha could you please approve it to run workflow? Thanks!

**Review by wbarnha — APPROVED** [review]
Thanks for updating the tests as well! LGTM!

**Comment by davidvanwyk** [comment]
@wbarnha - this has seemingly broken logging for me. Was working fine on 0.11.1 and now after this change I get no logging :/

**Comment by wbarnha** [comment]
I feared this would be the case. Looks like I missed this during testing. Does setting `worker_override_logging=False` in your settings fix your issue? I was contemplating setting that as the default.

**Comment by davidvanwyk** [comment]
@wbarnha - I haven't set up any form of custom logging. I'm using the defaults with no overrides and I invoke the worker as follows: 

```
python -m my_app worker -l info
```

I get the exact reverse behavior of the OP (what they were seeing in their linked issue I am now seeing after this change)

**Comment by wbarnha** [comment]
Well, that's a shame... I'll try to find a happy medium.

**Comment by lpogo** [comment]
@davidvanwyk could you confirm, that if you set `override_logging=True` in your `my_app` application, then logging is working fine again?
If yes, I think we should use `True` instead of `False` as default value. `mode.Worker` is using `True` as default, so it may be my bad I set it to `False`.
@wbarnha what do you think?

**Comment by davidvanwyk** [comment]
@lpogo - unfortunately not. I still get no logs other than the initial stdout with the Faust version etc.

**Comment by davidvanwyk** [comment]
Just to confirm - the setting you enabled on the application instance is: `worker_override_logging`. I think `override_logging` was what it was named in the context of CLI option?

**Comment by lpogo** [comment]
> Just to confirm - the setting you enabled on the application instance is: `worker_override_logging`. I think `override_logging` was what it was named in the context of CLI option?

Yes, you are right.

**Comment by davidvanwyk** [comment]
Well take a look and see if you can resolve this in the near term and @wbarnha can just roll forward, otherwise I think we need to roll this one back until it's been figured out? :) If I have some time in the coming days I can check it out as well but not 100% sure I will have the time.

**Comment by wbarnha** [comment]
I agree, I'm a bit confused on why this feature was necessary to begin with but I merged anyway since I figured it'd be harmless. We'll roll it back.

**Comment by lpogo** [comment]
Lets do it this way. This change mustn't impact current users. 
@wbarnha I found that it doesn't matter if `worker_override_logging` is set to `True` - `faust.Worker` is always receiving `False`. No idea why it is happening now..
Anyway for me logging issue started after #368 . Please take a look there.

**Comment by lesmanacflt** [comment]
This one hit me as well. Seems like now logging doesn't work. Rolling back to previous version.

**Comment by wbarnha** [comment]
Reverted changes in `faust-streaming==0.11.3`, thanks for your patience!

**Comment by wbarnha** [comment]
> Lets do it this way. This change mustn't impact current users. @wbarnha I found that it doesn't matter if `worker_override_logging` is set to `True` - `faust.Worker` is always receiving `False`. No idea why it is happening now.. Anyway for me logging issue started after #368 . Please take a look there.

I acknowledge the issue you're facing, we'll need to solve this some other way.

**Pull request merged**
