### PR TITLE
Complete fix rocksdb

### PR DESCRIPTION
**Pull request by xgamer4**
This completes the rocksdb fix for global tables and use_partitioner tables from https://github.com/faust-streaming/faust/pull/130

### CODE REVIEW

**Comment by taybin** [comment]
Is there a unit test that can be added for this?

**Comment by xgamer4** [comment]
> Is there a unit test that can be added for this?

Yeah, good call, looks like there's actually a few scenarios that should be added. I'll get those updated.

**Comment by xgamer4** [comment]
Added unit tests on both _get and _contains that cover the changes in this and #130

**Comment by taybin** [comment]
@xgamer4 Thanks for adding the tests! 👍

**Review by patkivikram — APPROVED** [review]

**Pull request merged**
