### PR TITLE
Global global tables

### PR DESCRIPTION
**Pull request by aoberegg**
## Description
If we use_partitioner and global tables it could happen that we write in Worker A to a partitions which is not active in Worker A but active in Worker B. To let Worker B consume the update we have to have all_partitions as standbys as well. 

A similar situation is happening if Global tables are shared over multiple consumer groups by using the possibility to pass a topic that should be used as changelog to the table. Consumer group A could write to the table and consumer group B, C, D only consuming. With the global_global flag it's possible to have shared state over multiple consumer groups.

As a side note. I'm happy if someone has better naming suggestions of the attribute :).

### CODE REVIEW

**Comment by wbarnha** [comment]
I like this idea! How about instead we change `is_global_global` to `synchronize_partitions`?

**Comment by wbarnha** [comment]
Potentially related issue? https://github.com/faust-streaming/faust/issues/283

**Comment by aoberegg** [comment]
Hm I'm not quite sure if this fixes https://github.com/faust-streaming/faust/issues/283. Because I think my fix only applies when a different worker writes into the partition of a table that is not his own active. 
Worker A --> actives(1,2), standbys(3,4)
Worker B --> actives(3,4), standbys(1,2)
If Worker A writes into the table partition 3. Then Worker B would not recognize the write because B's assumption is that he is the owner of that partition (as it's his active) and doesn't have to listen to the changelog because he is (assumed) anyway the only one writing to that partition. I'm not quite sure if a scenario like this is happening in https://github.com/faust-streaming/faust/issues/283 because they are not using "use_partitioner" and only writing to the partitions they are also receiving. 

For the naming. Maybe "synchronize_active_partitions" would be something declarative?

**Comment by wbarnha** [comment]
> Hm I'm not quite sure if this fixes #283.

Indeed it doesn't unfortunately, I had to read through your code more thoroughly,

> For the naming. Maybe "synchronize_active_partitions" would be something declarative?

Agreed, I'm much happier with that naming scheme. Once the naming is fixed, I'll be happy to merge in these changes.

**Review by wbarnha — CHANGES_REQUESTED** [review]
Requesting changes via this as a formality. Just change all references from `global_global` to `synchronize_active_partitions` or something equivalently and meaningfully named and we'll be golden!

**Review by wbarnha — APPROVED** [review]

**Pull request merged**
